
apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: clickhouse
      # username: username
      tlsSkipVerify: false
    secureJsonData:
      # password: password